### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'call' was called on null

### ISSUE THREAD

**Issue by Panagiss** [abhishekduhoon/custom_info_window#2]
The code is almost identical as in the docs:
```
void showInfoWindow(LatLng latLng) {
    return _customInfoWindowController.addInfoWindow(
      Column(
        children: [
          Expanded(
            child: Container(
              decoration: BoxDecoration(
                color: Colors.blue,
                borderRadius: BorderRadius.circular(4),
              ),
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      Icons.account_circle,
                      color: Colors.white,
                      size: 30,
                    ),
                    SizedBox(
                      width: 8.0,
                    ),
                    Text(
                      "I am here",
                      style: Theme.of(context).textTheme.headline6.copyWith(
                            color: Colors.white,
                          ),
                    )
                  ],
                ),
              ),
              width: double.infinity,
              height: double.infinity,
            ),
          ),
          Triangle.isosceles(
            edge: Edge.BOTTOM,
            child: Container(
              color: Colors.blue,
              width: 20.0,
              height: 10.0,
            ),
          ),
        ],
      ),
      latLng,
    );
  }
```

And the error is here:
```
V/Configuration(23879):  needToUpdateOverlays
E/flutter (23879): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (23879): Receiver: null
E/flutter (23879): Tried calling: call(Instance of 'Column', Instance of 'LatLng')
E/flutter (23879): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (23879): #1      _MapScreenState.showInfoWindow (package:flutter_firebase_chat_app/screens/map/map_screen.dart:165:53)
E/flutter (23879): #2      _MapScreenState.createMarkers.<anonymous closure> (package:flutter_firebase_chat_app/screens/map/map_screen.dart:50:20)
E/flutter (23879): #3      _GoogleMapState.onMarkerTap (package:google_maps_flutter/src/google_map.dart:344:31)
E/flutter (23879): #4      GoogleMapController._connectStreams.<anonymous closure> (package:google_maps_flutter/src/controller.dart:73:55)
E/flutter (23879): #5      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (23879): #6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (23879): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (23879): #8      CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
E/flutter (23879): #9      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (23879): #10     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (23879): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (23879): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23879): #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23879): #14     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23879): #15     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter (23879): #16     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23879): #17     _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (23879): #18     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (23879): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (23879): #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23879): #21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (23879): #22     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (23879): #23     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter (23879): #24     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (23879): #25     _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (23879): #26     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (23879): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (23879): #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (23879): #29     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (23879): #30     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (23879): #31     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (23879): #32     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (23879): #33     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (23879): #34     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (23879): #35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (23879): #36     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (23879): #37     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (23879): #38     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (23879): #39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (23879): #40     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (23879): #41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (23879): 
V/Configuration(23879):  needToUpdateOverlays
```

**Comment by Panagiss** [comment]
Sorry, but i found what was wrong. It was my mistake into the code! 
Feel free to delete the issue

**Comment by apoorvpandey0** [comment]
Can you tell how you fixed it? I'm facing the same issue. @Panagiss
