### ISSUE TITLE
Unhandled Exception: setState() called after dispose()

### ISSUE THREAD

**Issue by transtekuser09** [abhishekduhoon/custom_info_window#22]
Unhandled Exception: setState() called after dispose(): _CustomInfoWindowState#b902a(lifecycle state: defunct, not mounted)
E/flutter (22242): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (22242): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (22242): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (22242): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1167:9)
E/flutter (22242): #1      State.setState (package:flutter/src/widgets/framework.dart:1202:6)
E/flutter (22242): #2      _CustomInfoWindowState._hideInfoWindow (package:custom_info_window/custom_info_window.dart:117:5)
E/flutter (22242): #3      LiveTrackingListController.search (package:transtab_flutter/screens/live_tracking/live_tracking_list_controller.dart:177:45)
E/flutter (22242): <asynchronous suspension>

- "live_tracking_list_controller" this my dart where i have inplemented and "controllerInfoWindow" this is info window controller name
- giving ERROR HERE
 if (controllerInfoWindow.hideInfoWindow != null) {
        controllerInfoWindow.hideInfoWindow!(); <================== on this line
      }

- i have even disposed it still
 @override
  void dispose() {
    if (timer != null) {
      timer!.cancel();
      timer = null;
    }
    if (controllerInfoWindow.hideInfoWindow != null) {
      controllerInfoWindow.hideInfoWindow!();
    }
    controllerInfoWindow.dispose();
    super.dispose();
  }

**Comment by PhilipHuang2** [comment]
It looks like this package hasn't been maintained in a long time.

Version 1.01 was released in 2021, and the latest version of the github repository  was actually merged in 2024.

I've tried using the latest build and haven't experience this error in testing.  So it should be resolved if the package ever gets updated.
